### ISSUE TITLE
Unable to connect 

### ISSUE THREAD

**Issue by havchr** [loklaan/luxafor-for-slack#2]
Please wait. Checking for gravity.  luxafor-for-slack\node_modules\slack\methods\rtm.client.js:48
      bot.ws = new _ws2.default(data.url);
                                    ^
TypeError: Cannot read property 'url' of undefined
    at luxafor-for-slack\node_modules\slack\methods\rtm.client.js:48:37
    at Request._callback (luxafor-for-slack\node_modules\slack\methods\_exec.js:31:7)
    at Request.self.callback (luxafor-for-slack\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (luxafor-for-slack\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (luxafor-for-slack\node_modules\request\request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)

I am unsure if I have done the auth steps correct, I do have keys, client and secret. I enabled the DND permissions, but not others.

**Comment by loklaan** [comment]
Hey - I can't tell from this stack trace how the error occurred (it's depth only shows packages in node_modules).

Try getting a longer stack trace, and I'll try to help.

**Comment by Haraldson** [comment]
Any ideas on how I could get a longer stack trace here, @loklaan? Would love to help, but not sure how to proceed.

**Comment by loklaan** [comment]
The lofi debugging process is to jump your node_modules directory and start dropping `console.error()` in places.

It looks like [this module](https://github.com/smallwins/slack/blob/b0b64bf248b23df0a3d2d96b0b8077746eb3c1ac/src/_exec.js) is suppose to return the `data` object with a url prop. Try starting their in your local installation.

**Comment by aprevost** [comment]
I'm getting the exact same error. Was anyone able to figure out how to debug it?

**Comment by aprevost** [comment]
I investigated a bit more, this screenshot shows the specific error being returned by the slack package:

<img width="979" alt="screen shot 2018-06-12 at 7 31 34 pm" src="https://user-images.githubusercontent.com/5704741/41322530-642f1d70-6e77-11e8-94ab-0339fe177596.png">

I did some searching on the Slack API website, and couldn't figure out how to get rtm:stream added to the list of scopes for my application. This page says it comes with the bot scope:

https://api.slack.com/scopes/rtm:stream

But when I tried adding a bot to my app, that didn't fix the issue. If I used the "Bot User OAuth Access Token" instead of the app's more general "OAuth Access Token", the error didn't happen... but I think that's because it was retrieving the bot's DnD status in that case, not my own logged in user's DnD status.

**Comment by loklaan** [comment]
Oh yeah good find. (I gotta try that jetbrains debugger some day...)

If you ask for the `client` scope then you're implicitly given the `rtm:stream` scope. It was my understanding that the smallwins/slack package was asking for the `client` scope already 🤷‍♂️ odd...

Anyway, I hope that knowledge helps in some way, and please consider contributing back with a fix if you get there! Best of luck. I'll leave this issue around for a bit.
